"""empty message

Revision ID: 23478dadd468
Revises: be7e9bfca5d1
Create Date: 2022-09-14 13:18:51.089012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23478dadd468'
down_revision = 'be7e9bfca5d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'created')
    # ### end Alembic commands ###
