"""empty message

Revision ID: 336787f90c51
Revises: b6ef7900893c
Create Date: 2022-09-17 15:29:52.384768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336787f90c51'
down_revision = 'b6ef7900893c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('new_news', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_news', 'password')
    # ### end Alembic commands ###
