"""empty message

Revision ID: 5ab639fca601
Revises: 96344e0c6fe2
Create Date: 2022-09-17 16:42:48.355176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab639fca601'
down_revision = '96344e0c6fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hacker_jobs', sa.Column('updated', sa.Date(), nullable=True))
    op.add_column('new_news', sa.Column('updated', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('new_news', 'updated')
    op.drop_column('hacker_jobs', 'updated')
    # ### end Alembic commands ###
