"""empty message

Revision ID: 96344e0c6fe2
Revises: 336787f90c51
Create Date: 2022-09-17 15:30:31.357621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96344e0c6fe2'
down_revision = '336787f90c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hacker_jobs', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hacker_jobs', 'password')
    # ### end Alembic commands ###
