"""empty message

Revision ID: b6ef7900893c
Revises: 23478dadd468
Create Date: 2022-09-14 14:05:22.398316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ef7900893c'
down_revision = '23478dadd468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'level')
    # ### end Alembic commands ###
