"""empty message

Revision ID: be7e9bfca5d1
Revises: 2302a4911e3e
Create Date: 2022-09-14 13:16:25.713275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be7e9bfca5d1'
down_revision = '2302a4911e3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('item_id', sa.Integer(), nullable=False))
    op.drop_column('comments', 'com_itemid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('com_itemid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('comments', 'item_id')
    # ### end Alembic commands ###
